steps:
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - build
      - -t
      - us-central1-docker.pkg.dev/$PROJECT_ID/colectivo/admin-backend:latest
      - .

  - name: 'gcr.io/cloud-builders/docker'
    args: [push, 'us-central1-docker.pkg.dev/$PROJECT_ID/colectivo/admin-backend:latest']

images:
  - us-central1-docker.pkg.dev/$PROJECT_ID/colectivo/admin-backend:latest

options:
  logging: CLOUD_LOGGING_ONLY
